# Generated by Django 5.1 on 2024-08-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('images', models.ImageField(upload_to='edu')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'LessonImage',
                'db_table': 'lesson',
            },
        ),
    ]
